name = "fosdem-pwa-build-data"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-09-02"
workers_dev = false
preview_urls = false

[[r2_buckets]]
binding = "R2"
bucket_name = "fosdem"
preview_bucket_name = "fosdem"

[observability]
enabled = true

[triggers]
crons = [
    "*/15 8-17 1-2 2 *",
    "0 8-17 * 1 *",
    "0 0 * * *"
]